const fs = require('fs');
const path = require('path');

const projectRoot = path.resolve(__dirname, '..');
const resourcesDir = path.join(projectRoot, 'resources');
const outputFile = path.join(projectRoot, 'js', 'preset-thumbnails.js');

const THUMBNAIL_CANDIDATES = [
  'thumbnail.webp',
  'thumbnail.avif',
  'thumbnail.png',
  'thumbnail.jpg',
  'thumbnail.jpeg',
  // Safe fallback while real rendered thumbnails are being generated offline.
  'sky_front.jpg',
  'sky_front.png',
];

function collectPresetIds() {
  const entries = fs.readdirSync(resourcesDir, { withFileTypes: true });
  return entries
    .filter(entry => entry.isDirectory() && /^preset\d+$/.test(entry.name))
    .map(entry => Number.parseInt(entry.name.replace('preset', ''), 10))
    .filter(Number.isFinite)
    .sort((a, b) => a - b);
}

function resolveThumbnailFileName(presetDir) {
  for (const name of THUMBNAIL_CANDIDATES) {
    if (fs.existsSync(path.join(presetDir, name))) {
      return name;
    }
  }
  return null;
}

function buildThumbnailMap() {
  const map = {};
  for (const presetId of collectPresetIds()) {
    const presetDir = path.join(resourcesDir, `preset${presetId}`);
    const fileName = resolveThumbnailFileName(presetDir);
    map[presetId] = fileName ? `../resources/preset${presetId}/${fileName}` : null;
  }
  return map;
}

function toModuleSource(thumbnailMap) {
  const lines = [];
  lines.push('// Auto-generated by scripts/generate_embedded_preset_thumbnails.cjs');
  lines.push('const PRESET_THUMBNAIL_PATHS = {');

  for (const [presetId, relativePath] of Object.entries(thumbnailMap)) {
    if (relativePath) {
      lines.push(`  ${JSON.stringify(presetId)}: new URL(${JSON.stringify(relativePath)}, import.meta.url).href,`);
    } else {
      lines.push(`  ${JSON.stringify(presetId)}: null,`);
    }
  }

  lines.push('};');
  lines.push('');
  lines.push('export function getEmbeddedPresetThumbnailById(presetId) {');
  lines.push('  const key = Number.parseInt(`${presetId}`, 10);');
  lines.push('  if (!Number.isFinite(key) || !Object.hasOwn(PRESET_THUMBNAIL_PATHS, key)) {');
  lines.push('    return null;');
  lines.push('  }');
  lines.push('  return PRESET_THUMBNAIL_PATHS[key] || null;');
  lines.push('}');
  lines.push('');
  lines.push('export { PRESET_THUMBNAIL_PATHS };');
  lines.push('');

  return `${lines.join('\n')}\n`;
}

function main() {
  if (!fs.existsSync(resourcesDir)) {
    throw new Error(`Resources directory not found: ${resourcesDir}`);
  }

  const thumbnailMap = buildThumbnailMap();
  const source = toModuleSource(thumbnailMap);
  fs.writeFileSync(outputFile, source, 'utf8');

  const withThumbnail = Object.values(thumbnailMap).filter(Boolean).length;
  const total = Object.keys(thumbnailMap).length;
  console.log(
    `Generated ${path.relative(projectRoot, outputFile)} with ${withThumbnail}/${total} preset thumbnail path(s).`,
  );
}

main();
